# Generated by Django 3.0.14 on 2022-05-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_auto_20220516_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fourations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mode_tir', models.CharField(max_length=255)),
                ('type_tir', models.CharField(max_length=255)),
                ('mode_charge', models.CharField(max_length=255)),
                ('largeur', models.CharField(max_length=255)),
                ('nbr_trou_range', models.CharField(max_length=255)),
                ('tranche', models.CharField(max_length=255)),
                ('profondeur', models.CharField(max_length=255)),
                ('volume', models.CharField(max_length=255)),
                ('niveau', models.CharField(max_length=255)),
                ('nbr_trou', models.CharField(max_length=255)),
                ('maille', models.CharField(max_length=255)),
                ('panneau', models.CharField(max_length=255)),
                ('longueur', models.CharField(max_length=50)),
                ('nbr_range', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
