# Generated by Django 3.0.14 on 2022-05-16 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_fourations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='students',
            name='session_year_id',
        ),
    ]
