# Generated by Django 3.0.14 on 2022-05-16 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0009_auto_20220516_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='student_management_app.Courses'),
        ),
        migrations.AddField(
            model_name='students',
            name='session_year_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.SessionYearModel'),
            preserve_default=False,
        ),
    ]
