# Generated by Django 3.0.14 on 2022-05-17 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0010_auto_20220516_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fourations',
            old_name='volume',
            new_name='dossage',
        ),
    ]
